### PR TITLE
Resolves fixed TemplateExecutor parameters

### LINKED ISSUE #33: Enable update of the Map in the context for the mapping-template
If the map changes at every execution of the route (e.g., parameter coming from HTTP request) currently the context doesn't change

### PR DESCRIPTION
**Pull request by AuPath**
Should be merged after https://github.com/cefriel/mapping-template/pull/37.

Closes #33, #37.

### CODE REVIEW

File: camel-chimera-mapping-template/src/test/java/com/cefriel/MaptCustomFunctionsTest.java [hunk 1]
```diff
@@ -50,7 +51,7 @@ public void testCustomFunctionsResource() throws Exception {
         assert(result.equals("test"));
     }
 
-    @Test
+    @RepeatedTest(2)
```
Comment (marioscrock) [inline camel-chimera-mapping-template/src/test/java/com/cefriel/MaptCustomFunctionsTest.java:54]: great 👍

**Review by marioscrock — APPROVED** [review]
